### ISSUE TITLE
[extension] fix: Improve authentication from extension

### ISSUE THREAD

**Issue by lfaucon** [tournesol-app/tournesol#426] opened 2022-01-07 18:14 UTC
Currently user's are often logged out if they have not open the website and the extension only display an alert and does not help the user logging back in.

We should investigate how to better handle the login process from the extension

**Comment by GresilleSiffle** [comment] 2022-01-18 14:13
I've been able to reproduce this behaviour by following these steps. I don't know if I'm exploring the right path, can anyone confirm?

- log in to Tournesol
- from the API administration interface, I manually delete my access_token
- my access_token is still available in my browser local storage, but can't be used to make any request
- try to add a YT video to my rate later list -> this triggers an alert inviting me to log in

**Comment by lfaucon** [comment] 2022-01-18 21:59
I think you are on the right path. It seems to me that you are simulating your token expiring and that this is one of the main cause of extension not logged in for me that is easy to fix. I'd say this is the priority

I'm not sure about the following second issue:
- From a fully not logged-in browser with extension installed
- Try to rate later
- View alert (normal)
- open new tab tournesol.app
- user is not logged in (normal)
- login, then immediately switch to the youtube tab and try to add to rate later again

I think this scenario fails to be logged in in the extension on the final try and requires to refresh Tournesol's tab after having logged in (75% sure of this)

Third possible improvement is to show a more useful alert, maybe opening the tab automatically (a bit weird) or providing a 1-click button to the login page (probably best)

Note also that we should be careful not to mess-up the website's auth with the extension's auth ^^

**Comment by GresilleSiffle** [comment] 2022-01-19 10:25
Alright, if the pull request #481 is merged, both cases will trigger the same error message.

Note that I was not able to reproduce the case 2, everything went well 10 times in row.

> Third possible improvement is to show a more useful alert, maybe opening the tab automatically (a bit weird) or providing a 1-click button to the login page (probably best)

Sure. I'm currently following this path: (1) display a really useful alert in a first PR (2) investigate a sustainable fix in second PR.

> Note also that we should be careful not to mess-up the website's auth with the extension's auth ^^

I'll be careful : )

**Closed** 2022-01-31 12:38 UTC
Labels: Extension
