### ISSUE TITLE
(fix) Play Video with one click leads to autoplay in Contribute page

### ISSUE THREAD

**Issue by aidanjungo** [tournesol-app/tournesol#324] opened 2021-11-26 18:38 UTC
On the "Contribute" page, if the user click to watch one of the video and then click on the reload button to compare another video, the new video with be run automatically, it should not be the case.

**Comment by sandre35** [comment] 2021-12-03 14:15
@aidanjungo For me this is not the case on prod. Could you double check it pls ?

**Comment by sandre35** [comment] 2021-12-03 14:29
Ok the issue seems to be resolved with this PR : https://github.com/tournesol-app/tournesol/pull/322
So the issue is closed

**Closed by sandre35** 2021-12-03 14:29 UTC
Labels: Frontend
